services:
  neirogenapi:
    image: neirogenapi
    build:
      context: .
      dockerfile: NeiroGenApi/Dockerfile

  test:
    image: test
    build:
      context: .
      dockerfile: TEST/Dockerfile
